### PR TITLE
fix name for some movies with numbers only title

### PR DESCRIPTION
**Pull request by slick-nick-90**

### CODE REVIEW

**Comment by slick-nick-90** [comment]
Not sure how to fix it. I did not change those lines

**Comment by slick-nick-90** [comment]
@d-k-bo how should I proceed

**Comment by d-k-bo** [comment]
Sorry, I didn't find the time yet to review your PR.

**Comment by d-k-bo** [comment]
Thank you for your contribution! I just released version 0.3.1 to PyPI that includes these fixes.

**Pull request merged**
